# -*- coding: utf-8 -*-
"""DAY2 TASK

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jr_O0iGx-Ctef_fT5NqOMGo4AYyNL7Rt
"""



!pip install opencv-python matplotlib
import cv2
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()
img = cv2.imread(list(uploaded.keys())[0]) #Load image
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

plt.imshow(img)

cropped = img[100:400, 200:500]

rotated=cv2.rotate(img,cv2.ROTATE_90_CLOCKWISE)

plt.figure(figsize=(10,5))
plt.subplot(1,2,1);plt.imshow(img);plt.title("original")
plt. subplot(1,2,2);plt.imshow(rotated);plt.title("rotated")
plt.show()

gray=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
edges=cv2.Canny(gray,100,200)
plt.imshow(edges,cmap='gray')
plt.title("edgess detected!")
plt.show()





